image: node:latest

cache:
  paths:
    - node_modules/

services:
  - mongo:latest

variables:
  MONGO_URI: 'mongodb://mongo/seller-catalog'

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script:
    - npx mocha specs/spec.js
