image: node:latest

services:
  - mongo:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - node server/index.js

test:
  stage: test
  script:
    - npx mocha specs/spec.js
