version: '3'
services:
  server:
    image: node:14
    build: .
    ports:
      - '3002:3002'
    networks:
      - seller-catalog
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
      - '27017:27017'
    networks:
      - seller-catalog
networks:
  seller-catalog:
    driver: bridge